"""Initial migration

Revision ID: 3415bd9c7ef4
Revises: 
Create Date: 2025-06-08 13:49:29.516417

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3415bd9c7ef4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
