"""Add users table

Revision ID: 4e57336257bd
Revises: f0e0ca8462b0
Create Date: 2025-06-08 14:08:23.403367

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4e57336257bd'
down_revision = 'f0e0ca8462b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
