"""Add portfolio

Revision ID: edbb0699f9fd
Revises: 77ff21f225d4
Create Date: 2025-07-20 20:50:55.301451

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'edbb0699f9fd'
down_revision = '77ff21f225d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
