"""Add users table

Revision ID: f0e0ca8462b0
Revises: 3415bd9c7ef4
Create Date: 2025-06-08 14:01:25.006485

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f0e0ca8462b0'
down_revision = '3415bd9c7ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
