"""add portfolio and user models

Revision ID: f3721d1b50fe
Revises: fd8c6673e26a
Create Date: 2025-07-23 16:37:24.532886

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f3721d1b50fe'
down_revision = 'fd8c6673e26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
