"""add portfolio and user models

Revision ID: fd8c6673e26a
Revises: edbb0699f9fd
Create Date: 2025-07-23 16:36:13.200806

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fd8c6673e26a'
down_revision = 'edbb0699f9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cash_balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cash_balance')
    # ### end Alembic commands ###
